services:
  processor:
    build: ./processor
    devices:
      - /dev/video0:/dev/video0
    depends_on:
      - analyzer

  analyzer:
    build: ./analyzer

  webui:
    build: ./webui
    ports:
      - "8080:8080"
    depends_on:
      - analyzer
    profiles:
      - webui